# coding: utf-8

"""
Copyright 2016 SmartBear Software

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    Ref: https://github.com/swagger-api/swagger-codegen
"""

from pprint import pformat
from six import iteritems
import re


class ImageSoftware(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        ImageSoftware - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'license': 'str',
            'name': 'str',
            'id': 'str',
            'href': 'str',
            '_class': 'str'
        }

        self.attribute_map = {
            'license': 'license',
            'name': 'name',
            'id': 'id',
            'href': 'href',
            '_class': '_class'
        }

        self._license = None
        self._name = None
        self._id = None
        self._href = None
        self.__class = None

    @property
    def license(self):
        """
        Gets the license of this ImageSoftware.


        :return: The license of this ImageSoftware.
        :rtype: str
        """
        return self._license

    @license.setter
    def license(self, license):
        """
        Sets the license of this ImageSoftware.


        :param license: The license of this ImageSoftware.
        :type: str
        """
        
        self._license = license

    @property
    def name(self):
        """
        Gets the name of this ImageSoftware.


        :return: The name of this ImageSoftware.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this ImageSoftware.


        :param name: The name of this ImageSoftware.
        :type: str
        """
        
        self._name = name

    @property
    def id(self):
        """
        Gets the id of this ImageSoftware.


        :return: The id of this ImageSoftware.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this ImageSoftware.


        :param id: The id of this ImageSoftware.
        :type: str
        """
        
        self._id = id

    @property
    def href(self):
        """
        Gets the href of this ImageSoftware.


        :return: The href of this ImageSoftware.
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href):
        """
        Sets the href of this ImageSoftware.


        :param href: The href of this ImageSoftware.
        :type: str
        """
        
        self._href = href

    @property
    def _class(self):
        """
        Gets the _class of this ImageSoftware.


        :return: The _class of this ImageSoftware.
        :rtype: str
        """
        return self.__class

    @_class.setter
    def _class(self, _class):
        """
        Sets the _class of this ImageSoftware.


        :param _class: The _class of this ImageSoftware.
        :type: str
        """
        
        self.__class = _class

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other

